NAME = dreamJob

CXX = c++
CXXFLAGS = -Wall -Wextra -Werror -std=c++98

SRCS = tests.cpp \
	   Account.cpp \

OBJS = $(SRCS:.cpp=.o)

HEADERS = Account.hpp

all: $(NAME)

$(NAME): $(OBJS)
	$(CXX) $(CXXFLAGS) $(OBJS) -o $(NAME)

%.o: %.cpp $(HEADERS)
	$(CXX) $(CXXFLAGS) -c $< -o $@

clean:
	rm -f $(OBJS)

fclean: clean
	rm -f $(NAME)

re: fclean all

.PHONY: all cleann fclean re